package nft_item

import "open_sea_be/model"

var items = []model.NFTItem{
	{
		ID:           "ef89ebe7-b9e1-41ed-a506-350cc90d9a70",
		Name:         "Red",
		Description:  "Taylor Swift's Red Album Cover (Official). Get access to own the cover piece in the Metaverse World",
		CategoryID:   model.NFTCategoryArt,
		Price:        125,
		Owner:        "Taylor Swift",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:           "998ad7a4-a87f-46ea-a85f-11daf1699cb2",
		Name:         "1989",
		Description:  "Taylor Swift's 1989 Album Cover (Official). Get access to own the cover piece in the Metaverse World",
		CategoryID:   model.NFTCategoryMusic,
		Price:        123,
		Owner:        "Taylor Swift",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:   "f6c9ddba-1995-4002-9499-62c34102b97c",
		Name: "鄧麗君-我只在乎你",
		Description: "Metaverse Music Record, Teresa Teng's #2 song record ownership in Metaverse. When purchased, every song listened will pay royalty to the " +
			"official minter and the current owner of the item",
		CategoryID:   model.NFTCategoryMusic,
		Price:        210,
		Owner:        "鄧麗君",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:   "37ab82b7-f7ca-4089-9b62-ea5852c8ebdb",
		Name: "劉若英-为爱痴狂 (Metaverse Music Record)",
		Description: "Metaverse Music Record, Liu Ruo Ying's #1 song record ownership in Metaverse. When purchased, every song listened will pay royalty to the " +
			"official minter and the current owner of the item",
		CategoryID:   model.NFTCategoryMusic,
		Price:        225,
		Owner:        "劉若英",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:           "82287dbf-00eb-4795-b665-3f0a66d9ac71",
		Name:         "Taipei 101 Building (Metaverse - Sandbox)",
		Description:  "Sandbox Metaverse Platform item for Taipei 101 Building",
		CategoryID:   model.NFTCategoryVirtualWorld,
		Price:        25,
		Owner:        "夏琳",
		VerifiedUser: model.VerifiedUserNFTFalse,
	},
	{
		ID:           "d589e7c9-7e8b-4076-bf80-dd4f66b739cb",
		Name:         "明朝剑",
		Description:  "正品. 创建于 1467 年",
		CategoryID:   model.NFTCategoryRealWorldOwnership,
		Price:        7,
		Owner:        "張栢芝",
		VerifiedUser: model.VerifiedUserNFTFalse,
	},
	{
		ID:           "0f52513e-eb7e-48c5-913a-de36664069f0",
		Name:         "红旗CN123 Car 2004",
		Description:  "红旗CN123 used car made in 2004. Serial number : 91200102091KF. Verify the car authenticity at 红旗 official website",
		CategoryID:   model.NFTCategoryRealWorldOwnership,
		Price:        13,
		Owner:        "胡一天",
		VerifiedUser: model.VerifiedUserNFTFalse,
	},
	{
		ID:           "baa33ca9-a5e6-42ab-96c2-45367c179cc3",
		Name:         "Playground Monkey",
		Description:  "Playground Monkey Collection",
		CategoryID:   model.NFTCategoryArt,
		Price:        76,
		Owner:        "Cool Monkey Co",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:           "24a71a36-4f73-4c58-a66f-ef422a24e940",
		Name:         "Killertronaut Spacesuit",
		Description:  "Killertronaut Spaceship designed by famous NFT Street artist John McLarren",
		CategoryID:   model.NFTCategoryArt,
		Price:        93,
		Owner:        "Nautica Co.",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:           "4387c1dc-8500-4ca7-ad61-ea1574451423",
		Name:         "Eternity by Astha District 8",
		Description:  "Apartment block sale in Astha District 8 residence. Eternity tower apartment, 2 Bedroom, 1 Bathroom, 1 Lounge, 1 working space.",
		CategoryID:   model.NFTCategoryRealWorldOwnership,
		Price:        93,
		Owner:        "ASRI Group",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
}

var topItems = []model.NFTItem{
	{
		ID:           "ef89ebe7-b9e1-41ed-a506-350cc90d9a70",
		Name:         "Red",
		Description:  "Taylor Swift's Red Album Cover (Official). Get access to own the cover piece in the Metaverse World",
		CategoryID:   model.NFTCategoryArt,
		Price:        125,
		Owner:        "Taylor Swift",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:           "998ad7a4-a87f-46ea-a85f-11daf1699cb2",
		Name:         "1989",
		Description:  "Taylor Swift's 1989 Album Cover (Official). Get access to own the cover piece in the Metaverse World",
		CategoryID:   model.NFTCategoryMusic,
		Price:        123,
		Owner:        "Taylor Swift",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:           "baa33ca9-a5e6-42ab-96c2-45367c179cc3",
		Name:         "Playground Monkey",
		Description:  "Playground Monkey Collection",
		CategoryID:   model.NFTCategoryArt,
		Price:        46,
		Owner:        "Cool Monkey Co",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:           "24a71a36-4f73-4c58-a66f-ef422a24e940",
		Name:         "Killertronaut Spacesuit",
		Description:  "Killertronaut Spaceship designed by famous NFT Street artist John McLarren",
		CategoryID:   model.NFTCategoryArt,
		Price:        23,
		Owner:        "Nautica Co.",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
	{
		ID:           "4387c1dc-8500-4ca7-ad61-ea1574451423",
		Name:         "Eternity by Astha District 8",
		Description:  "Apartment block sale in Astha District 8 residence. Eternity tower apartment, 2 Bedroom, 1 Bathroom, 1 Lounge, 1 working space.",
		CategoryID:   model.NFTCategoryRealWorldOwnership,
		Price:        93,
		Owner:        "ASRI Group",
		VerifiedUser: model.VerifiedUserNFTTrue,
	},
}
